+++
title = "À propos..."
date = "2017-07-17"
menu = "main"
+++
:icons: font

L'objectif de ce site est de proposer du contenu en rapport avec mon activité d'enseignant dans la spécialité **Informatique & Réseaux** du **BTS Systèmes Numériques**.

Cette spécialité aborde les thèmes des réseaux et de leur sécurité, des systèmes embarqués, du _cloud computing_ et de la programmation des systèmes.

Ce site représente un moyen de centraliser puis de partager des ressources et des informations qui m'ont servi ou qui m'ont simplement intéressé à un moment ou à un autre dans le cadre de mon activité.

Bonne lecture...  

[NOTE]
.À propos du terme "Pervasion"
=====
En premier lieu, il faut savoir qu'il ne fait pas partie de la langue française. C'est un néologisme qui viendrait de l'anglais _pervasive_ qui pourrait se traduire par "omniprésent"

Les mauvaises langues pourraient dire qu'il constitue aussi une contraction de *__perv__erse* et *in__vasion__* icon:smile-o[]

Cependant, quelle que soit la signification qu'on lui accorde, le résultat est le même : le numérique est partout autour de nous, pour le meilleur ou pour le pire...
=====

[cols="^",frame="none",options="header"]
|=====
|[red]#icon:power-off[2x]#
|=====
