+++
title = "À propos..."
date = "2017-07-17"
menu = "main"
+++
:icons: font

L'objectif de ce site est de proposer du contenu en rapport avec mon activité d'enseignant en **BTS Systèmes Numériques**.

Cette formation dispose de 2 spécialités :

. Informatique & Réseaux
. Électronique & Communications

La 1^ère^ aborde les thèmes des réseaux et de leur sécurité, des systèmes embarqués, du _cloud computing_ et de la programmation des systèmes.

La 2^ème^ traite de la commande rapprochée, de l’usage des composants complexes, de la pré-industrialisation des dispositifs électroniques, de leur maintenance, et de la mobilisation des moyens de télécommunication dans les couches de bas niveau.

Ce site représente un moyen de centraliser puis de partager des retours d'expérience, ressources et informations sur des domaines techniques en rapport avec mon activité.

Bonne lecture...  

[NOTE]
.À propos du terme "`Pervasion`"
=====
En premier lieu, il faut savoir qu'il ne fait pas partie de la langue française. C'est un néologisme qui viendrait de l'anglais _pervasive_ qui pourrait se traduire par "`omniprésent`"

Les mauvaises langues pourraient dire qu'il constitue aussi une contraction de *__perv__erse* et *in__vasion__* avec la connotation négative que véhicule cette interprétation.

Cependant, quelle que soit la signification qu'on accorde à "`Pervasion`", le constat est le même :
le numérique est bel et bien partout autour de nous, pour le meilleur ... ou pour le pire icon:smile-o[].
=====

[cols="^",frame="none",options="header"]
|=====
|[red]#icon:power-off[2x]#
|=====
